### ISSUE TITLE
Train Data

### ISSUE THREAD

**Issue by bcba25** [deepcam-cn/Face-Anti-spoofing.pytorch#1]
Hi, Thanks for sharing your code, could you reupload training data somewhere else? baidu is extremely slow, less than 1kb/sec. Would be nice if you can upload on google drive. Thanks

**Comment by liurs1990** [comment]
I've uploaded it to google drive. 
https://drive.google.com/file/d/1CUG9HK75oGYxQn81RU8H-zjscZy8ozMp/view?usp=sharing
