### ISSUE TITLE
您好 您能不能提供一下您的环境的版本信息？

### ISSUE THREAD

**Issue by silvercherry** [deepcam-cn/Face-Anti-spoofing.pytorch#12]

**Comment by liurs1990** [comment]
我当时是用的pytorch 1.0， cuda9.0，使用更新的版本应该也没有问题

**Comment by silvercherry** [comment]
> 我当时是用的pytorch 1.0， cuda9.0，使用更新的版本应该也没有问题

好的 谢谢您 请问您这边有测试的代码吗 我看您这里这有训练代码
