### ISSUE TITLE
transforms for image and depth are not sync together

### ISSUE THREAD

**Issue by gdjmck** [deepcam-cn/Face-Anti-spoofing.pytorch#13]
I notice that the transforms for image data and depth data are not the same, there would be RandomResizedCrop for image data and just Resize for depth data. Wouldn't it lead to mismatch pixels for the generated depth and the ground truth depth?

**Comment by liurs1990** [comment]
Yes, it leads to a mismatch between the depth map and RGB image. But the mismatch is tiny.
