### ISSUE TITLE
How can i get the prob when i input one image

### ISSUE THREAD

**Issue by heyanglearning** [deepcam-cn/Face-Anti-spoofing.pytorch#14]
1. I train the net with the data your provided,
2. load the checkpoint and preproess the img, output = net(x)
3. how can i get the real or fake prob with output

**Comment by liurs1990** [comment]
You can get the final score like codes blow

 output, class_ret = net(input)
        class_ret = class_ret.detach().cpu()
        class_output = nn.functional.softmax(class_ret, dim = 1)
        score = class_output[0][1]

**Comment by sahilrider** [comment]
How to preprocess image so as to infer from the model?

**Comment by sahilrider** [comment]
> How to preprocess image so as to infer from the model? I am doing this but it says.
> 
> **RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 3, 3, 3], but got 3-dimensional input of size [3, 128, 128] instead
> **
> 
> ```
> img = Image.open(img_path).convert('RGB')
> img = random_input_transform(img)
> img = img.cuda(device)
> output, class_ret = net(img)
> class_ret = class_ret.detach().cpu()
> class_output = nn.functional.softmax(class_ret, dim=1)
> score = class_output[0][1]
> print(score)
> ```

Solved by adding this line
img = torch.unsqueeze(img, 0)

**Comment by sahilrider** [comment]
> You can get the final score like codes blow
> 
> output, class_ret = net(input)
> class_ret = class_ret.detach().cpu()
> class_output = nn.functional.softmax(class_ret, dim = 1)
> score = class_output[0][1]

score = 0 should be fake and score = 1 should be live. Right?

**Comment by liurs1990** [comment]
> > You can get the final score like codes blow
> > output, class_ret = net(input)
> > class_ret = class_ret.detach().cpu()
> > class_output = nn.functional.softmax(class_ret, dim = 1)
> > score = class_output[0][1]
> 
> score = 0 should be fake and score = 1 should be live. Right?

the score woule be between 0 and 1. you can set an threshold(0.5), the score of live face will be greater than threshold.
