### ISSUE TITLE
安卓demo 和训练的模型的效果好像不一样啊

### ISSUE THREAD

**Issue by smartwell** [deepcam-cn/Face-Anti-spoofing.pytorch#15]
首先非常非常感谢,作者的开源精神,再次感谢.
我运行了安卓的demo,效果是很好的,也看了一下输出的信息,想不明白为何要keep static 呢? 感觉安卓demo和训练的模型运行机制不一样啊,
我训练了模型,也理解了作者的意图,引入了depth 信息,但是测试的时候效果不及安卓demo,还请大佬指点一下

**Comment by smartwell** [comment]
是不是multi frame 模式

**Comment by liurs1990** [comment]
Android demo中的模型是使用更多的数据训练出来的模型

**Comment by luan1412167** [comment]
> The model in the Android demo is a model trained with more data

How many samples did you train the model?

**Comment by luan1412167** [comment]
@smartwell did you train successfully with the model?

**Comment by smartwell** [comment]
yes, no problem

> @smartwell did you train successfully with the model?

the face samples cames from author. i can train this model.
