### ISSUE TITLE
The so files question

### ISSUE THREAD

**Issue by KevinAnnn** [deepcam-cn/Face-Anti-spoofing.pytorch#19]
Hello up , can you publish the so source code? Now I don't know how to implement data processing.

**Comment by liurs1990** [comment]
It's very convenient to do data processing with MNN after getting the face image Mat:
```
const float mean_vals[3] = { 123.675f, 116.28f, 103.53f };
const float norm_vals[3] = { 0.0171247538f, 0.0175070028f, 0.0174291939f };
...
                ::memcpy(img_config.mean, mean_vals, sizeof(mean_vals));
		::memcpy(img_config.normal, norm_vals, sizeof(norm_vals));
		img_config.sourceFormat = (MNN::CV::ImageFormat)2;
		img_config.destFormat = (MNN::CV::ImageFormat)1;
		img_config.filterType = (MNN::CV::Filter)(1);
		img_config.wrap = (MNN::CV::Wrap)(1);
...
	//prepare data
	std::shared_ptr<MNN::CV::ImageProcess> pretreat(MNN::CV::ImageProcess::create(img_config));
	pretreat->convert(img.data, 128, 128, img.step[0], input_tensor);
```

**Comment by KevinAnnn** [comment]
> It's very convenient to do data processing with MNN after getting the face image Mat:
> 
> ```
> const float mean_vals[3] = { 123.675f, 116.28f, 103.53f };
> const float norm_vals[3] = { 0.0171247538f, 0.0175070028f, 0.0174291939f };
> ...
>                 ::memcpy(img_config.mean, mean_vals, sizeof(mean_vals));
> 		::memcpy(img_config.normal, norm_vals, sizeof(norm_vals));
> 		img_config.sourceFormat = (MNN::CV::ImageFormat)2;
> 		img_config.destFormat = (MNN::CV::ImageFormat)1;
> 		img_config.filterType = (MNN::CV::Filter)(1);
> 		img_config.wrap = (MNN::CV::Wrap)(1);
> ...
> 	//prepare data
> 	std::shared_ptr<MNN::CV::ImageProcess> pretreat(MNN::CV::ImageProcess::create(img_config));
> 	pretreat->convert(img.data, 128, 128, img.step[0], input_tensor);
> ```

Thank you very much.
