### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by bcba25** [deepcam-cn/Face-Anti-spoofing.pytorch#2]
Could you reupload dataset anywhere else, baidu is too slow. Thanks

**Comment by liurs1990** [comment]
I've uploaded it to google drive.
https://drive.google.com/file/d/1CUG9HK75oGYxQn81RU8H-zjscZy8ozMp/view?usp=sharing

**Comment by bcba25** [comment]
@liurs1990 alright thanks! Btw which camera is used to capture depth data ?

**Comment by liurs1990** [comment]
@hxdef2517  It's RGB face anti-spoofing without depth camera. You can get the depth information of  RGB frame by PRNET.

**Comment by bcba25** [comment]
@liurs1990 I see, got it. I've read the paper but can't get one simple thing ) when we do training and set depth map to 0 for all fake images, what does this gives us when we try to predict on trained model ? Is it something like, real images got a good depth but then when we try to predict on fake on it will not have that good depth comparing to the real one? Could you explain this particular part please )))

**Comment by liurs1990** [comment]
Yes,  the ideal result is getting a depth image on the real face and dark image on the fake face, but the depth image isn't the final result. We need the score of classifier instead of depth image.

**Comment by bcba25** [comment]
@liurs1990 alright, thanks for clarification and sharing the codes 👍
