### ISSUE TITLE
about the multi-frame code

### ISSUE THREAD

**Issue by emmmisme** [deepcam-cn/Face-Anti-spoofing.pytorch#3]
what's going on about the multi-frame algorithm ?

**Comment by liurs1990** [comment]
We are working on it

**Comment by bcba25** [comment]
@liurs1990 guys, are you going to commit changes here regarding multi-frame code in a future ?

**Comment by Amadeus-AI** [comment]
Is there any update?

**Comment by liurs1990** [comment]
We are not going to share the multi-frames code
